import { useState, useMemo } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  Share2,
  Copy,
  Download,
  Maximize2,
  Minimize2,
  Search,
  Save,
  RefreshCw,
  AlertTriangle,
  History,
  Sparkles,
  CheckCircle2,
  DollarSign,
  Shield,
  Layers,
  ChevronDown,
  Scale,
  ExternalLink,
} from "lucide-react";
import { Button } from "@ui/index";
import { cn } from "@utils/index";

export interface CardItem {
  title: string;
  description: string;
  details?: string[];
  codeBlock?: string;
  icon?: any;
}

export interface CostRow {
  category: string;
  monthly: number;
}

export interface Vulnerability {
  title: string;
  severity: "critical" | "high" | "medium" | "low" | "info";
  description: string;
  solution: string;
}

interface GeneratorReportProps {
  title: string;
  summary: string;
  visualization?: React.ReactNode;
  breakdown: CardItem[];
  cost?: CostRow[];
  recommendations: string[];
  security: Vulnerability[];
  onRefresh?: () => void;
  onSave?: () => void;
  exportFormat?: string;
}

export function GeneratorReport({
  title,
  summary,
  visualization,
  breakdown,
  cost,
  recommendations,
  security,
  onRefresh,
  onSave,
}: GeneratorReportProps) {
  const [searchQuery, setSearchQuery] = useState("");
  const [isFullscreen, setIsFullscreen] = useState(false);
  const [isSaved, setIsSaved] = useState(false);
  const [isCopied, setIsCopied] = useState(false);
  const [isShared, setIsShared] = useState(false);
  const [showHistory, setShowHistory] = useState(false);
  const [compareMode, setCompareMode] = useState(false);
  const [collapsedCards, setCollapsedCards] = useState<Set<string>>(new Set());

  // Mock version history
  const historyList = [
    { id: 1, date: "2 minutes ago", author: "DevCanvas AI", prompt: "Initial build request" },
    { id: 2, date: "10 minutes ago", author: "DevCanvas AI", prompt: "Refactored draft" },
  ];

  const handleCopyReport = async () => {
    const formatted = `
# ${title} Report
## Executive Summary
${summary}

## Recommendations
${recommendations.map((r) => `* ${r}`).join("\n")}

## Security
${security
  .map(
    (v) => `### [${v.severity.toUpperCase()}] ${v.title}\nDescription: ${v.description}\nSolution: ${v.solution}`
  )
  .join("\n\n")}
`;
    await navigator.clipboard.writeText(formatted);
    setIsCopied(true);
    setTimeout(() => setIsCopied(false), 2000);
  };

  const handleShare = () => {
    const tempUrl = window.location.href;
    navigator.clipboard.writeText(tempUrl);
    setIsShared(true);
    setTimeout(() => setIsShared(false), 2000);
  };

  const handleSaveAction = () => {
    if (onSave) onSave();
    setIsSaved(true);
    setTimeout(() => setIsSaved(false), 3000);
  };

  const toggleCard = (cardTitle: string) => {
    const next = new Set(collapsedCards);
    if (next.has(cardTitle)) {
      next.delete(cardTitle);
    } else {
      next.add(cardTitle);
    }
    setCollapsedCards(next);
  };

  // Filter breakdown and security items based on search query
  const filteredBreakdown = useMemo(() => {
    if (!searchQuery.trim()) return breakdown;
    const query = searchQuery.toLowerCase();
    return breakdown.filter(
      (item) =>
        item.title.toLowerCase().includes(query) ||
        item.description.toLowerCase().includes(query) ||
        item.details?.some((d) => d.toLowerCase().includes(query))
    );
  }, [breakdown, searchQuery]);

  const filteredSecurity = useMemo(() => {
    if (!searchQuery.trim()) return security;
    const query = searchQuery.toLowerCase();
    return security.filter(
      (item) =>
        item.title.toLowerCase().includes(query) ||
        item.description.toLowerCase().includes(query) ||
        item.solution.toLowerCase().includes(query)
    );
  }, [security, searchQuery]);

  const totalCostMonthly = useMemo(() => {
    if (!cost) return 0;
    return cost.reduce((sum, row) => sum + row.monthly, 0);
  }, [cost]);

  const reportContainer = (
    <div className={cn("space-y-8 pb-16", isFullscreen && "bg-background/95 p-8 overflow-y-auto max-h-screen")}>
      {/* Dynamic Header Controls */}
      <div className="flex flex-col gap-4 border-b border-white/5 pb-5 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h2 className="font-heading text-lg font-semibold text-neutral-100 flex items-center gap-2">
            <Sparkles className="h-4.5 w-4.5 text-indigo-400" />
            {title} Report
          </h2>
          <p className="text-xs text-neutral-400 mt-1">Generated by DevCanvas AI platform</p>
        </div>

        <div className="flex flex-wrap gap-2">
          <Button variant="outline" size="sm" onClick={handleSaveAction}>
            <Save className="h-4 w-4" />
            {isSaved ? "Saved" : "Save Report"}
          </Button>

          <Button variant="outline" size="sm" onClick={() => setShowHistory(!showHistory)}>
            <History className="h-4 w-4" />
            History
          </Button>

          <Button variant="outline" size="sm" onClick={() => setCompareMode(!compareMode)}>
            <Scale className="h-4 w-4" />
            Compare
          </Button>

          <Button variant="outline" size="sm" onClick={handleShare}>
            <Share2 className="h-4 w-4" />
            {isShared ? "Link Copied" : "Share"}
          </Button>

          <Button variant="outline" size="sm" onClick={handleCopyReport}>
            <Copy className="h-4 w-4" />
            {isCopied ? "Copied" : "Copy MD"}
          </Button>

          <div className="relative group">
            <Button variant="outline" size="sm">
              <Download className="h-4 w-4" />
              Export As
            </Button>
            <div className="absolute right-0 top-full mt-1.5 hidden w-40 flex-col rounded-lg border border-white/10 bg-surface-2 p-1 text-xs text-neutral-400 shadow-xl group-hover:flex z-50">
              <button className="rounded px-2.5 py-1.5 text-left hover:bg-white/5 hover:text-white">PDF Document</button>
              <button className="rounded px-2.5 py-1.5 text-left hover:bg-white/5 hover:text-white">JSON Metadata</button>
              <button className="rounded px-2.5 py-1.5 text-left hover:bg-white/5 hover:text-white">Markdown File</button>
              <button className="rounded px-2.5 py-1.5 text-left hover:bg-white/5 hover:text-white">Mermaid Diagram</button>
              {title.toLowerCase().includes("database") && (
                <button className="rounded px-2.5 py-1.5 text-left hover:bg-white/5 hover:text-white">SQL Schema DDL</button>
              )}
            </div>
          </div>

          {onRefresh && (
            <Button variant="ghost" size="sm" onClick={onRefresh}>
              <RefreshCw className="h-4 w-4 animate-spin-hover" />
            </Button>
          )}

          <Button variant="ghost" size="sm" onClick={() => setIsFullscreen(!isFullscreen)}>
            {isFullscreen ? <Minimize2 className="h-4 w-4" /> : <Maximize2 className="h-4 w-4" />}
          </Button>
        </div>
      </div>

      {/* Version History Drawer */}
      <AnimatePresence>
        {showHistory && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: "auto", opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            className="rounded-xl border border-white/10 bg-white/[0.02] p-4 overflow-hidden"
          >
            <h4 className="font-heading text-xs font-semibold uppercase tracking-wider text-neutral-400 mb-2">Version History</h4>
            <div className="space-y-2">
              {historyList.map((h) => (
                <div key={h.id} className="flex items-center justify-between rounded-lg bg-surface px-4 py-2 text-xs border border-white/5">
                  <div>
                    <span className="font-medium text-white/90">Version {h.id}</span>
                    <span className="mx-2 text-neutral-600">|</span>
                    <span className="text-neutral-500">{h.prompt}</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <span className="text-neutral-500">{h.date}</span>
                    <button className="text-indigo-400 hover:underline">Revert</button>
                  </div>
                </div>
              ))}
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Compare View Mode */}
      {compareMode && (
        <div className="rounded-xl border border-dashed border-white/10 p-4 bg-indigo-500/5 text-center text-xs text-indigo-300">
          ⚖️ Compare mode active. Showing differences between current version and draft.
        </div>
      )}

      {/* Live Search Inside Report */}
      <div className="relative">
        <Search className="absolute left-3.5 top-1/2 h-4 w-4 -translate-y-1/2 text-neutral-500" />
        <input
          type="text"
          value={searchQuery}
          onChange={(e) => setSearchQuery(e.target.value)}
          placeholder="Search inside generated report sections..."
          className="w-full rounded-xl border border-white/10 bg-white/[0.03] pl-10 pr-4 py-2.5 text-xs text-neutral-100 placeholder:text-neutral-500 focus:outline-none focus:ring-1 focus:ring-indigo-500"
        />
      </div>

      {/* Section 1: Executive Summary */}
      <section className="rounded-xl border border-white/10 bg-white/[0.02] p-5.5 shadow-lg relative overflow-hidden group">
        <div className="absolute inset-0 bg-gradient-to-r from-indigo-500/5 to-purple-500/5 opacity-0 group-hover:opacity-100 transition-opacity duration-500" />
        <h3 className="font-heading text-xs font-extrabold uppercase tracking-widest text-emerald-400 mb-3 flex items-center gap-1.5">
          <Sparkles className="h-4 w-4" />
          Executive Summary
        </h3>
        <p className="text-sm text-neutral-200 leading-relaxed font-sans">{summary}</p>
      </section>

      {/* Section 2: Interactive Visualization */}
      {visualization && (
        <section className="space-y-3">
          <h3 className="font-heading text-xs font-extrabold uppercase tracking-widest text-neutral-400">
            Interactive Visualization
          </h3>
          <div className="rounded-2xl border border-white/10 bg-black/40 overflow-hidden shadow-2xl relative h-[450px]">
            {visualization}
          </div>
        </section>
      )}

      {/* Section 3: Detailed Breakdown Cards */}
      <section className="space-y-4">
        <h3 className="font-heading text-xs font-extrabold uppercase tracking-widest text-neutral-400">
          Detailed Breakdown
        </h3>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {filteredBreakdown.map((card, idx) => {
            const isCollapsed = collapsedCards.has(card.title);
            const CardIcon = card.icon || Layers;
            return (
              <motion.div
                key={idx}
                layout
                className="gradient-border rounded-xl group relative overflow-hidden"
              >
                <div className="glass-strong rounded-xl p-5 space-y-3.5">
                  <div
                    className="flex items-center justify-between cursor-pointer"
                    onClick={() => toggleCard(card.title)}
                  >
                    <div className="flex items-center gap-3">
                      <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-emerald-500/10 text-emerald-400 group-hover:scale-105 transition-transform">
                        <CardIcon className="h-5 w-5" />
                      </div>
                      <h4 className="text-base font-bold text-white tracking-tight">{card.title}</h4>
                    </div>
                    <ChevronDown className={cn("h-4.5 w-4.5 text-neutral-400 transition-transform duration-200", isCollapsed && "rotate-180")} />
                  </div>

                  {!isCollapsed && (
                    <motion.div
                      initial={{ opacity: 0, height: 0 }}
                      animate={{ opacity: 1, height: "auto" }}
                      className="space-y-3"
                    >
                      <p className="text-sm text-neutral-300 leading-relaxed">{card.description}</p>
                      {card.details && card.details.length > 0 && (
                        <ul className="space-y-2">
                          {card.details.map((detail, dIdx) => (
                            <li key={dIdx} className="text-xs text-neutral-200 flex items-start gap-2">
                              <span className="h-1.5 w-1.5 rounded-full bg-emerald-400 mt-1.5 shrink-0" />
                              {detail}
                            </li>
                          ))}
                        </ul>
                      )}
                      {card.codeBlock && (
                        <div className="relative rounded-lg bg-black/60 border border-white/5 p-3.5 overflow-x-auto text-xs font-mono text-emerald-200 group-code mt-2">
                          <button
                            onClick={async () => {
                              await navigator.clipboard.writeText(card.codeBlock || "");
                            }}
                            className="absolute right-2 top-2 p-1.5 rounded border border-white/10 bg-white/5 hover:bg-white/10 text-neutral-400 hover:text-white"
                          >
                            <Copy className="h-3.5 w-3.5" />
                          </button>
                          <pre>{card.codeBlock}</pre>
                        </div>
                      )}
                    </motion.div>
                  )}
                </div>
              </motion.div>
            );
          })}
        </div>
      </section>

      {/* Section 4: Cost Estimation */}
      {cost && cost.length > 0 && (
        <section className="space-y-4">
          <h3 className="font-heading text-xs font-extrabold uppercase tracking-widest text-neutral-400">
            Cost Estimation
          </h3>
          <div className="rounded-xl border border-white/10 bg-white/[0.02] overflow-hidden">
            <table className="w-full text-left text-sm border-collapse">
              <thead>
                <tr className="border-b border-white/10 bg-white/5 text-neutral-200 font-semibold">
                  <th className="px-5 py-3.5">Infrastructure Category</th>
                  <th className="px-5 py-3.5 text-right">Estimated Monthly Cost</th>
                  <th className="px-5 py-3.5 text-right">Estimated Yearly Cost</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-white/5 text-neutral-300">
                {cost.map((row, idx) => (
                  <tr key={idx} className="hover:bg-white/[0.02]">
                    <td className="px-5 py-3.5 flex items-center gap-2 font-medium">
                      <span className="h-1.5 w-1.5 rounded-full bg-emerald-500" />
                      {row.category}
                    </td>
                    <td className="px-5 py-3.5 text-right text-neutral-100 font-mono">${row.monthly.toFixed(2)}</td>
                    <td className="px-5 py-3.5 text-right text-neutral-300 font-mono">${(row.monthly * 12).toFixed(2)}</td>
                  </tr>
                ))}
                <tr className="bg-white/5 font-bold text-white">
                  <td className="px-5 py-4 flex items-center gap-2">
                    <DollarSign className="h-4.5 w-4.5 text-emerald-400" />
                    Total Infrastructure Cost
                  </td>
                  <td className="px-5 py-4 text-right text-emerald-400 font-mono">${totalCostMonthly.toFixed(2)}/mo</td>
                  <td className="px-5 py-4 text-right text-emerald-400/80 font-mono">${(totalCostMonthly * 12).toFixed(2)}/yr</td>
                </tr>
              </tbody>
            </table>
          </div>
        </section>
      )}

      {/* Section 5: Recommendations */}
      <section className="space-y-4">
        <h3 className="font-heading text-xs font-extrabold uppercase tracking-widest text-neutral-400">
          AI Recommendations
        </h3>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {recommendations.map((rec, idx) => (
            <div key={idx} className="flex gap-3.5 rounded-xl border border-white/5 bg-white/[0.01] p-4.5 items-start hover:border-white/10 transition-colors">
              <span className="flex h-5.5 w-5.5 shrink-0 items-center justify-center rounded-full bg-emerald-500/10 text-emerald-400 mt-0.5">
                <CheckCircle2 className="h-4 w-4" />
              </span>
              <p className="text-sm text-neutral-200 font-sans leading-relaxed">{rec}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Section 6: Security Review */}
      <section className="space-y-4">
        <h3 className="font-heading text-xs font-extrabold uppercase tracking-widest text-neutral-400">
          Security Review
        </h3>
        <div className="grid grid-cols-1 gap-4">
          {filteredSecurity.map((v, idx) => {
            const severityColor =
              v.severity === "critical"
                ? "bg-rose-500/15 text-rose-400 border-rose-500/30"
                : v.severity === "high"
                ? "bg-amber-500/15 text-amber-400 border-amber-500/30"
                : "bg-emerald-500/15 text-emerald-400 border-emerald-500/30";
            return (
              <div key={idx} className="rounded-xl border border-white/10 bg-white/[0.01] p-5 space-y-3.5 relative overflow-hidden group">
                <div className="absolute inset-y-0 left-0 w-1 bg-gradient-to-b from-emerald-500 to-teal-500" />
                <div className="flex items-center justify-between gap-3">
                  <h4 className="text-base font-bold text-white">{v.title}</h4>
                  <span className={cn("rounded-full border px-3 py-0.5 text-xs font-extrabold uppercase tracking-wider", severityColor)}>
                    {v.severity}
                  </span>
                </div>
                <p className="text-sm text-neutral-300 leading-relaxed font-sans">{v.description}</p>
                <div className="rounded-lg bg-surface/50 p-3.5 border border-white/5 space-y-1.5">
                  <span className="text-xs font-bold uppercase tracking-wider text-neutral-400">Suggested Solution</span>
                  <p className="text-sm text-neutral-200 leading-relaxed font-sans">{v.solution}</p>
                </div>
              </div>
            );
          })}
        </div>
      </section>
    </div>
  );

  return (
    <div className={cn(isFullscreen && "fixed inset-0 z-50 bg-black overflow-y-auto")}>
      {reportContainer}
    </div>
  );
}
