import { useState, useMemo } from "react";
import {
  Download,
  CheckCircle2,
  FileCode,
  Zap,
  Bot,
  Cpu,
  Sparkles,
  Terminal,
  Wand2,
  FileText,
  Copy,
  Check,
  Package,
} from "lucide-react";
import { Badge, Button } from "@ui/index";
import type { Project } from "@types-pkg/index";
import { cn } from "@utils/index";

const EXPORT_TARGET_AIS = [
  { id: "devcanvas", name: "🚀 AI Project Package (.devcanvas)", desc: "Native portable DevCanvas spec bundle with complete metadata", icon: Zap },
  { id: "chatgpt", name: "🤖 Export for ChatGPT", desc: "Optimized system prompt & markdown specification for GPT-4o", icon: Bot },
  { id: "claude", name: "🧠 Export for Claude", desc: "XML-tagged structured system prompt for Claude 3.5 Sonnet", icon: Cpu },
  { id: "gemini", name: "♊ Export for Gemini", desc: "Clean markdown context bundle for Gemini 2.5/3.0", icon: Sparkles },
  { id: "cursor", name: "⚡ Export for Cursor", desc: ".cursorrules & project context prompt file for Cursor IDE", icon: Terminal },
  { id: "copilot", name: "🐙 Export for Copilot", desc: "GitHub Copilot instructions & architecture context doc", icon: FileCode },
  { id: "windsurf", name: "🌀 Export for Windsurf", desc: "Cascade AI rules & code generation context package", icon: Wand2 },
];

export function BlueprintCenterTab({ project }: { project: Project }) {
  const [selectedFormat, setSelectedFormat] = useState<"devcanvas" | "markdown" | "json" | "html" | "sql">("devcanvas");
  const [selectedAI, setSelectedAI] = useState<string>("devcanvas");
  const [copiedFormat, setCopiedFormat] = useState(false);

  const readiness = useMemo(() => {
    const items = [
      { name: "Architecture Specification", ready: !!project.architecture, key: "arch" },
      { name: "PostgreSQL Database Schema", ready: !!project.database_schema, key: "db" },
      { name: "OpenAPI 3.0 REST Specification", ready: !!project.api_spec, key: "api" },
      { name: "OWASP Security Audit", ready: !!project.security_report, key: "sec" },
      { name: "Docker & Kubernetes Deployment Plan", ready: !!project.deployment_plan, key: "dep" },
      { name: "Developer Documentation Suite", ready: !!project.documentation, key: "docs" },
    ];
    const completed = items.filter((i) => i.ready).length;
    const score = Math.round((completed / items.length) * 100);
    return { items, completed, score };
  }, [project]);

  const generateBlueprintText = (format: string) => {
    if (format === "json" || format === "devcanvas") {
      return JSON.stringify(
        {
          devcanvas_version: "2.0",
          project: {
            id: project.id,
            name: project.name,
            description: project.description,
            created_at: project.created_at,
          },
          architecture: project.architecture ?? null,
          database_schema: project.database_schema ?? null,
          api_spec: project.api_spec ?? null,
          security_report: project.security_report ?? null,
          deployment_plan: project.deployment_plan ?? null,
          documentation: project.documentation ?? null,
        },
        null,
        2
      );
    }

    if (format === "sql") {
      const tables = project.database_schema?.tables || [];
      if (!tables.length) return "-- No Database Tables Defined --";
      return tables
        .map((t: any) => {
          const cols = (t.columns || [])
            .map((c: any) => `  ${c.name} ${c.type}${c.primaryKey ? " PRIMARY KEY" : ""}${c.nullable ? "" : " NOT NULL"}`)
            .join(",\n");
          return `CREATE TABLE ${t.name} (\n${cols}\n);`;
        })
        .join("\n\n");
    }

    return `# ${project.name} - Engineering Blueprint Specification
Generated by DevCanvas AI Command Center

## Project Overview
${project.description || "No project description provided."}

## Architecture Blueprint
${project.architecture ? JSON.stringify(project.architecture.services || [], null, 2) : "Not generated."}

## Database Entities
${project.database_schema ? JSON.stringify(project.database_schema.tables || [], null, 2) : "Not generated."}

## API Endpoints
${project.api_spec ? JSON.stringify(project.api_spec.endpoints || [], null, 2) : "Not generated."}
`;
  };

  const handleExportBlueprint = () => {
    const content = generateBlueprintText(selectedFormat);
    const ext = selectedFormat === "markdown" ? "md" : selectedFormat === "sql" ? "sql" : selectedFormat === "html" ? "html" : "json";
    const mime = selectedFormat === "markdown" ? "text/markdown" : "application/json";

    const blob = new Blob([content], { type: mime });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${project.name.toLowerCase().replace(/\s+/g, "-")}-blueprint.${ext}`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleCopyPrompt = () => {
    const content = generateBlueprintText(selectedFormat);
    navigator.clipboard.writeText(content);
    setCopiedFormat(true);
    setTimeout(() => setCopiedFormat(false), 2000);
  };

  return (
    <div className="space-y-8 text-left">
      {/* Top Banner */}
      <div className="rounded-2xl border border-white/10 bg-gradient-to-b from-white/[0.03] to-transparent p-6 sm:p-8">
        <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
          <div>
            <div className="flex items-center gap-2">
              <Package className="h-5 w-5 text-indigo-400" />
              <h2 className="font-heading text-lg font-bold text-white">Engineering Blueprint Center</h2>
              <Badge variant="outline" className="border-indigo-500/30 text-indigo-300 bg-indigo-500/10">
                Export &amp; Target AI Presets
              </Badge>
            </div>
            <p className="text-xs text-neutral-400 mt-1 max-w-xl">
              Consolidate your entire software specification package for developer handoff, automated coding tools (Cursor, Windsurf), or external AI models (ChatGPT, Claude, Gemini).
            </p>
          </div>

          <div className="flex items-center gap-3">
            <Button variant="outline" size="sm" onClick={handleCopyPrompt} className="text-xs flex items-center gap-1">
              {copiedFormat ? <Check className="h-3.5 w-3.5 text-emerald-400" /> : <Copy className="h-3.5 w-3.5" />}
              {copiedFormat ? "Copied Spec!" : "Copy Spec Text"}
            </Button>
            <Button variant="gradient" size="sm" onClick={handleExportBlueprint} className="text-xs flex items-center gap-1.5">
              <Download className="h-3.5 w-3.5" />
              Generate &amp; Download Blueprint
            </Button>
          </div>
        </div>
      </div>

      {/* Blueprint Readiness Matrix */}
      <div className="rounded-2xl border border-white/10 bg-white/[0.02] p-6 space-y-4">
        <div className="flex items-center justify-between">
          <h3 className="font-heading text-xs font-bold uppercase tracking-wider text-neutral-300">
            Blueprint Readiness Matrix
          </h3>
          <span className="font-heading text-base font-extrabold text-emerald-400">{readiness.score}% Complete</span>
        </div>

        <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-3">
          {readiness.items.map((item) => (
            <div key={item.key} className="flex items-center justify-between p-3 rounded-xl border border-white/5 bg-neutral-950 text-xs">
              <span className="text-neutral-200 font-medium">{item.name}</span>
              <Badge variant={item.ready ? "success" : "outline"} className="text-[9.5px]">
                {item.ready ? "Ready" : "Missing"}
              </Badge>
            </div>
          ))}
        </div>
      </div>

      {/* Target AI Preset Exporter */}
      <div className="space-y-4">
        <h3 className="font-heading text-xs font-bold uppercase tracking-wider text-neutral-300">
          Select Target AI / IDE Export Format
        </h3>

        <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-3">
          {EXPORT_TARGET_AIS.map((target) => (
            <div
              key={target.id}
              onClick={() => setSelectedAI(target.id)}
              className={cn(
                "group cursor-pointer rounded-xl border p-4 transition-all space-y-2 select-none",
                selectedAI === target.id
                  ? "border-primary-500/50 bg-primary-500/10 text-white"
                  : "border-white/10 bg-white/[0.02] hover:border-white/20 hover:bg-white/[0.04] text-neutral-300"
              )}
            >
              <div className="flex items-center justify-between">
                <span className="font-bold text-xs flex items-center gap-2">
                  <target.icon className="h-4 w-4 text-primary-400" />
                  {target.name}
                </span>
                {selectedAI === target.id && <CheckCircle2 className="h-4 w-4 text-primary-400" />}
              </div>
              <p className="text-[11px] text-neutral-400 leading-normal">{target.desc}</p>
            </div>
          ))}
        </div>
      </div>

      {/* Format Selector & Preview */}
      <div className="rounded-2xl border border-white/10 bg-neutral-950 p-6 space-y-4">
        <div className="flex flex-wrap items-center justify-between gap-3 border-b border-white/10 pb-4">
          <span className="text-xs font-bold uppercase text-neutral-300 tracking-wider">Raw Output Format:</span>
          <div className="flex flex-wrap gap-2 text-xs">
            {(["devcanvas", "markdown", "json", "sql"] as const).map((fmt) => (
              <button
                key={fmt}
                onClick={() => setSelectedFormat(fmt)}
                className={cn(
                  "px-3 py-1 rounded-lg border font-semibold uppercase text-[10.5px] transition-colors",
                  selectedFormat === fmt
                    ? "border-primary-500 bg-primary-500/20 text-primary-300"
                    : "border-white/10 bg-white/[0.03] text-neutral-400 hover:text-white"
                )}
              >
                .{fmt}
              </button>
            ))}
          </div>
        </div>

        <div className="rounded-xl border border-white/5 bg-neutral-900/60 p-4 font-mono text-xs text-neutral-300 max-h-60 overflow-y-auto whitespace-pre-wrap">
          {generateBlueprintText(selectedFormat)}
        </div>
      </div>
    </div>
  );
}
