import { useState, useMemo } from "react";
import { useNavigate } from "react-router-dom";
import {
  FolderKanban,
  Activity,
  TrendingUp,
  Boxes,
  Zap,
  Clock,
  Plus,
  Search,
  Command,
  ArrowUpRight,
  ExternalLink,
  Layers,
  ChevronRight,
  Lock,
  Globe,
  Share2,
  RefreshCw,
  SlidersHorizontal,
} from "lucide-react";
import { PageHeader } from "@/components/dashboard/page-header";
import { QuickActions } from "@/components/dashboard/quick-actions";
import { StatCard } from "@/components/dashboard/stat-card";
import { ProjectCardSkeleton, EmptyProjects } from "@/components/dashboard/project-card";
import { GraphiteAnimatedBackground } from "@/components/dashboard/graphite-animated-background";
import { useProjects } from "@/lib/queries/projects";
import { useRecentActivity } from "@/lib/queries/activity";
import { useAuth } from "@/lib/auth-context";
import { cn } from "@utils/cn";
import { Badge } from "@ui/index";

// Pipeline stage definitions — status derived from a project's actual artifact columns
const PIPELINE_STAGE_DEFS = [
  { id: "planning",      label: "Planning",      artifactKey: null },
  { id: "architecture",  label: "Architecture",  artifactKey: "architecture" },
  { id: "database",      label: "Database",      artifactKey: "database_schema" },
  { id: "api",           label: "API Specs",     artifactKey: "api_spec" },
  { id: "security",      label: "Security",      artifactKey: "security_report" },
  { id: "documentation", label: "Documentation", artifactKey: "documentation" },
  { id: "deployment",    label: "Deployment",    artifactKey: "deployment_plan" },
] as const;

/** Derives pipeline stages for the most-recently-active project */
function deriveProjectPipeline(project: any) {
  let foundCurrent = false;
  return PIPELINE_STAGE_DEFS.map((stg) => {
    // Planning is always complete once a project exists
    if (stg.artifactKey === null) return { ...stg, status: "complete" as const };
    const hasArtifact = !!(project as any)?.[stg.artifactKey];
    if (hasArtifact) return { ...stg, status: "complete" as const };
    if (!foundCurrent) {
      foundCurrent = true;
      return { ...stg, status: "current" as const };
    }
    return { ...stg, status: "upcoming" as const };
  });
}

/** Calculates an engineering completeness score (0-100) from artifact presence */
function calcEngineeringScore(project: any): number {
  const artifacts = ["architecture", "database_schema", "api_spec", "security_report", "documentation", "deployment_plan"];
  const completed = artifacts.filter((key) => !!(project as any)?.[key]).length;
  return Math.round((completed / artifacts.length) * 100);
}

/** Extracts actual tech stack from architecture services or specification */
function extractTechStack(project: any): string[] {
  // Prefer architecture.services technologies (generated by AI)
  const services: any[] = project?.architecture?.services ?? [];
  if (services.length > 0) {
    const techs = [...new Set(services.map((s: any) => s.technology).filter(Boolean))] as string[];
    if (techs.length > 0) return techs.slice(0, 5);
  }
  // Fall back to specification.techStack if set during project creation
  const specStack: string[] = project?.specification?.techStack ?? [];
  if (specStack.length > 0) return specStack.slice(0, 5);
  // Fall back to specification answers if available
  const answers = project?.specification?.answers;
  if (answers?.technology) return [answers.technology].flat().slice(0, 5);
  return [];
}

export function DashboardHomePage() {
  const { profile } = useAuth();
  const { data: projects, isLoading } = useProjects();
  const { data: activity } = useRecentActivity();
  const navigate = useNavigate();

  // Search & Filter State
  const [searchQuery, setSearchQuery] = useState("");
  const [activityFilter, setActivityFilter] = useState<string | null>(null);

  // Client-side project search filter
  const filteredProjects = useMemo(() => {
    if (!projects) return [];
    let list = [...projects];
    if (searchQuery.trim()) {
      const q = searchQuery.toLowerCase();
      list = list.filter(
        (p) =>
          p.name.toLowerCase().includes(q) ||
          p.description?.toLowerCase().includes(q)
      );
    }
    return list.slice(0, 6);
  }, [projects, searchQuery]);

  // Client-side activity logs filtering
  const filteredActivities = useMemo(() => {
    if (!activity) return [];
    if (!activityFilter) return activity.slice(0, 5);
    const filterTerm = activityFilter.toLowerCase();
    return activity
      .filter((act) => act.content.toLowerCase().includes(filterTerm))
      .slice(0, 5);
  }, [activity, activityFilter]);

  return (
    <div className="relative min-h-screen z-10 space-y-12 pb-20 font-sans tracking-tight antialiased">
      {/* ── Precision Ambient Graphite grid ── */}
      <GraphiteAnimatedBackground />

      {/* Utilise maximum left and right space of the dashboard page */}
      <div className="relative z-10 w-full px-6 lg:px-12 space-y-10">
        
        {/* ── Page Header & Hero Title ── */}
        <div className="relative pt-10 pb-4">
          {/* Subtle Invisible Radial Glow backdrop */}
          <div
            className="absolute -top-12 left-1/3 h-[320px] w-[450px] rounded-full opacity-25 pointer-events-none"
            style={{
              background: "radial-gradient(circle, rgba(124, 92, 255, 0.15) 0%, rgba(59, 130, 246, 0.05) 60%, transparent 100%)",
              filter: "blur(50px)",
            }}
          />

          <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
            <div className="space-y-1.5 text-left">
              <h1 className="font-heading text-3xl font-extrabold tracking-tight text-white sm:text-4xl bg-clip-text">
                Welcome back, {profile?.full_name?.split(" ")[0] ?? "engineer"}
              </h1>
              <p className="text-sm text-neutral-400">
                Your AI engineering workspace. Generate, analyze, and ship production-ready architectures.
              </p>
            </div>
            <button
              onClick={() => navigate("/app/projects/new")}
              className="flex items-center gap-2 rounded-lg bg-indigo-500 hover:bg-indigo-600 px-4 py-2 text-xs font-bold text-white transition-all shadow-[0_4px_12px_rgba(99,102,241,0.15)] active:scale-[0.98]"
            >
              <Plus className="h-4 w-4" /> New Project
            </button>
          </div>
        </div>

        {/* ── Search Command Bar Widget ── */}
        <div className="relative group max-w-3xl">
          <div className="absolute inset-0 bg-gradient-to-r from-indigo-500/10 to-blue-500/10 rounded-xl blur-md opacity-35 group-hover:opacity-50 transition-opacity" />
          <div className="relative flex items-center bg-[#09090B] border border-white/10 rounded-xl px-3.5 py-2.5 shadow-xl">
            <Search className="h-4.5 w-4.5 text-neutral-500 mr-2.5" />
            <input
              type="text"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              placeholder="Search projects, blueprints, technical specifications or type Ctrl + K..."
              className="w-full bg-transparent text-sm text-white placeholder-neutral-500 focus:outline-none"
            />
            <div className="hidden sm:flex items-center gap-1 border border-white/10 bg-white/[0.04] rounded px-1.5 py-0.5 text-[10px] text-neutral-400 font-mono">
              <Command className="h-3 w-3" />
              <span>K</span>
            </div>
          </div>
        </div>

        {/* ── Statistics Cards with top borders ── */}
        <div className="grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-4">
          <StatCard
            label="Total Projects"
            value={projects?.length ?? 0}
            delta={`${projects?.filter((p) => p.status === "active").length ?? 0} active blueprints`}
            deltaType="up"
            icon={FolderKanban}
            colorType="border-t-2 border-t-indigo-500"
            onClick={() => navigate("/app/projects")}
          />
          <StatCard
            label="AI Generations"
            value={activity?.length ?? 0}
            delta="Completed artifact scans"
            deltaType="up"
            icon={Boxes}
            colorType="border-t-2 border-t-blue-500"
            onClick={() => navigate("/app/chat")}
          />
          <StatCard
            label="Avg. Security Rating"
            value="A"
            delta="Zero critical vulnerabilities"
            deltaType="up"
            icon={TrendingUp}
            colorType="border-t-2 border-t-emerald-500"
            onClick={() => navigate("/app/security")}
          />
          <StatCard
            label="Active blue-prints"
            value={
              projects?.filter((p) => {
                const updated = new Date(p.updated_at ?? p.created_at);
                return Date.now() - updated.getTime() < 7 * 24 * 60 * 60 * 1000;
              }).length ?? 0
            }
            delta="updated in the last 7d"
            deltaType="neutral"
            icon={Zap}
            colorType="border-t-2 border-t-amber-500"
            onClick={() => navigate("/app/projects")}
          />
        </div>

        {/* ── Quick Action Generator Modules ── */}
        <div className="space-y-4">
          <h2 className="text-xs font-bold uppercase tracking-wider text-neutral-500 flex items-center gap-1.5">
            <Layers className="h-4 w-4" /> Quick Actions Spec Generators
          </h2>
          <QuickActions />
        </div>

        {/* ── Horizontal Progress Spec Widget — derived from most active project artifacts ── */}
        {(() => {
          const activeProject = projects?.[0] ?? null;
          const stages = activeProject ? deriveProjectPipeline(activeProject) : PIPELINE_STAGE_DEFS.map(s => ({ ...s, status: "upcoming" as const }));
          const currentStage = stages.find(s => s.status === "current");
          return (
            <div className="rounded-xl border border-white/5 bg-[#09090B] p-5 space-y-4 shadow-sm text-left">
              <div className="flex justify-between items-center">
                <span className="text-[10px] font-bold uppercase tracking-wider text-neutral-550">Engineering Delivery Pipeline</span>
                <span className="text-[10.5px] text-neutral-450 font-mono">
                  {activeProject
                    ? currentStage
                      ? `Next: ${currentStage.label}`
                      : "All artifacts generated ✓"
                    : "Create a project to begin"}
                </span>
              </div>

              <div className="grid grid-cols-2 md:grid-cols-7 gap-2 pt-2">
                {stages.map((stg) => (
                  <div
                    key={stg.id}
                    className={cn(
                      "p-3 rounded-lg border text-xs font-semibold transition-all",
                      stg.status === "complete"
                        ? "border-teal-500/20 bg-teal-500/5 text-teal-300"
                        : stg.status === "current"
                        ? "border-amber-500/30 bg-amber-500/10 text-white font-bold"
                        : "border-white/5 bg-white/[0.01] text-neutral-550"
                    )}
                  >
                    <div className="flex items-center gap-1.5">
                      <span
                        className={cn(
                          "h-1.5 w-1.5 rounded-full",
                          stg.status === "complete" ? "bg-teal-400" : stg.status === "current" ? "bg-amber-400 animate-pulse" : "bg-neutral-600"
                        )}
                      />
                      <span>{stg.label}</span>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          );
        })()}

        {/* ── Recent Projects Grid with Stack Badges & Actions ── */}
        <div className="space-y-4 text-left">
          <div className="flex items-center justify-between">
            <h2 className="text-[10px] font-bold uppercase tracking-wider text-neutral-500">
              Recent specifications
            </h2>
            <button
              onClick={() => navigate("/app/projects")}
              className="text-xs font-semibold text-neutral-455 hover:text-white transition-colors"
            >
              View all
            </button>
          </div>

          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
            {isLoading ? (
              Array.from({ length: 3 }).map((_, i) => <ProjectCardSkeleton key={i} />)
            ) : filteredProjects.length === 0 ? (
              <div className="col-span-full">
                <EmptyProjects />
              </div>
            ) : (
              filteredProjects.map((project) => {
                const engScore = calcEngineeringScore(project);
                const techStack = extractTechStack(project);
                return (
                  <div
                    key={project.id}
                    className="group relative rounded-xl border border-white/10 bg-[#09090B] hover:border-teal-500/30 transition-all p-5 flex flex-col justify-between"
                  >
                    <div className="space-y-3">
                      <div className="flex justify-between items-start">
                        <h3 className="font-heading text-base font-bold text-white group-hover:text-teal-400 transition-colors">
                          {project.name}
                        </h3>
                        <Badge
                          variant="outline"
                          className={cn(
                            "text-[10px] font-bold",
                            engScore === 0
                              ? "border-neutral-600/30 text-neutral-500"
                              : engScore < 50
                              ? "border-amber-500/30 text-amber-400"
                              : "border-emerald-500/20 text-emerald-400"
                          )}
                        >
                          {engScore === 0 ? "No artifacts" : `Score ${engScore}%`}
                        </Badge>
                      </div>

                      <p className="text-xs text-neutral-400 line-clamp-2 leading-relaxed">
                        {project.description || "No project description provided."}
                      </p>

                      {/* Tech stack badges — derived from AI-generated architecture or project specification */}
                      <div className="flex flex-wrap gap-1.5 pt-0.5">
                        {techStack.length > 0 ? (
                          techStack.map((tech) => (
                            <span
                              key={tech}
                              className="text-[10px] font-semibold text-neutral-450 bg-white/5 border border-white/5 rounded px-2 py-0.5"
                            >
                              {tech}
                            </span>
                          ))
                        ) : (
                          <span className="text-[10px] text-neutral-600 italic">
                            Generate architecture to reveal stack
                          </span>
                        )}
                      </div>
                    </div>

                    <div className="mt-5 pt-3.5 border-t border-white/5 flex items-center justify-between text-xs">
                      <span className="text-[10.5px] text-neutral-500 font-medium">
                        Updated {new Date(project.updated_at).toLocaleDateString()}
                      </span>
                      <button
                        onClick={() => navigate(`/app/projects/${project.id}`)}
                        className="flex items-center gap-1 text-xs text-teal-400 hover:text-teal-300 font-bold transition-colors"
                      >
                        Open Workspace <ChevronRight className="h-3.5 w-3.5" />
                      </button>
                    </div>
                  </div>
                );
              })
            )}
          </div>
        </div>

        {/* ── Activity Feed Filter Timeline ── */}
        <div className="grid grid-cols-1 gap-4 lg:grid-cols-2 text-left">
          
          {/* Timeline Activity card */}
          <div className="rounded-xl border border-white/5 bg-[#09090B] p-5 space-y-4 shadow-sm">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-white/5 pb-3">
              <div className="flex items-center gap-2">
                <Activity className="h-4.5 w-4.5 text-indigo-400" />
                <h3 className="font-heading text-xs font-bold uppercase tracking-wider text-neutral-450">
                  Recent activities timeline
                </h3>
              </div>

              {/* Filters */}
              <div className="flex flex-wrap gap-1 text-[10px] font-bold">
                {["Architecture", "Database", "API", "Security"].map((cat) => (
                  <button
                    key={cat}
                    onClick={() => setActivityFilter(activityFilter === cat ? null : cat)}
                    className={cn(
                      "px-2 py-0.5 rounded border transition-colors",
                      activityFilter === cat
                        ? "bg-indigo-500/10 border-indigo-500 text-indigo-300"
                        : "bg-white/5 border-white/10 text-neutral-405 hover:text-white"
                    )}
                  >
                    {cat}
                  </button>
                ))}
              </div>
            </div>

            {filteredActivities.length > 0 ? (
              <div className="relative pl-4 border-l border-white/15 space-y-4 py-2 font-sans text-xs">
                {filteredActivities.map((item) => (
                  <div key={item.id} className="relative space-y-1">
                    <span className="absolute -left-[20.5px] top-1.5 h-2.5 w-2.5 rounded-full border border-[#09090B] bg-indigo-500" />
                    <div className="flex justify-between items-center gap-3">
                      <span className="text-xs text-neutral-300">{item.content}</span>
                      <span className="text-[10px] text-neutral-500 font-mono shrink-0">
                        {new Date(item.created_at).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                      </span>
                    </div>
                  </div>
                ))}
              </div>
            ) : (
              <div className="text-xs text-neutral-550 py-4">No matching timeline logs found.</div>
            )}
          </div>

          {/* Quick Platform Stats card */}
          <div className="rounded-xl border border-white/5 bg-[#09090B] p-5 space-y-4 shadow-sm">
            <div className="flex items-center gap-2 border-b border-white/5 pb-3">
              <TrendingUp className="h-4.5 w-4.5 text-emerald-400" />
              <h3 className="font-heading text-xs font-bold uppercase tracking-wider text-neutral-450">
                Blueprint specifications by status
              </h3>
            </div>

            {projects && projects.length > 0 ? (
              <div className="space-y-4">
                {(["active", "draft", "archived"] as const).map((status) => {
                  const count = projects.filter((p) => p.status === status).length;
                  const pct = projects.length ? Math.round((count / projects.length) * 100) : 0;
                  const barColors = {
                    active: "bg-indigo-500",
                    draft: "bg-amber-500",
                    archived: "bg-neutral-600",
                  };
                  return (
                    <div key={status}>
                      <div className="mb-1.5 flex justify-between text-xs font-sans">
                        <span className="capitalize text-neutral-450 font-semibold">{status}</span>
                        <span className="text-neutral-350 font-mono">{count}</span>
                      </div>
                      <div className="relative h-1 w-full overflow-hidden rounded-full bg-white/5">
                        <div
                          className={`h-full rounded-full ${barColors[status]} transition-[width] duration-300`}
                          style={{ width: `${pct}%` }}
                        />
                      </div>
                    </div>
                  );
                })}
              </div>
            ) : (
              <div className="flex h-32 items-center justify-center text-xs text-neutral-550">
                No active projects recorded.
              </div>
            )}
          </div>
        </div>

      </div>
    </div>
  );
}
